---
- name: Patch Servers
  hosts: servers

  tasks:
  - name: Upgrade all apt packages
    apt: state=latest force_apt_get=yes

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
